import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Counter } from "../features/Counter/Counter";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <nav className="font-sans flex flex-col text-center sm:flex-row sm:text-left sm:justify-between py-4 px-6 bg-white shadow sm:items-baseline w-full">
            <div className="mb-2 sm:mb-0">
              <a
                href="/home"
                className="text-2xl no-underline text-grey-darkest hover:text-blue-dark"
              >
                Home
              </a>
            </div>
            <div>
              <Link href="/products">
                <a className=" hover:underline text-lg no-underline text-grey-darkest hover:text-blue-dark mx-2">
                  Product
                </a>
              </Link>
              <Link href="/signin">
                <a className="hover:underline text-lg no-underline text-grey-darkest hover:text-blue-dark mx-2">
                  Signin
                </a>
              </Link>
              <Link href="/signup">
                <a className="hover:underline text-lg no-underline text-grey-darkest hover:text-blue-dark mx-2">
                  Signup
                </a>
              </Link>
            </div>
          </nav>
        </div>
        <div>
          <Counter />
        </div>
      </main>
    </div>
  );
};

export default Home;
